### ISSUE TITLE
ICanPay

### ISSUE THREAD

**Issue by Varorbc** [milanyangbo/ICanPay#2]
我也是借鉴了这个作者的代码，然后改了很多东西，最近准备增加银联支付，因为银联里面实在太多加密等东西，没法跨平台，所以在github上找看有没有相关资源，就看到了你的项目
https://github.com/Varorbc/ICanPay

**Comment by milanyangbo** [comment]
我已对代码做了优化，支持NET46和NETSTANDARD2_0

**Comment by Varorbc** [comment]
你的Gateways是从我哪里复制过去的吧

**Comment by milanyangbo** [comment]
对参考了你的思路。但是我们解决跨平台的方式不同

**Comment by Varorbc** [comment]
可以考虑合并吗？一起来做这个项目

**Comment by milanyangbo** [comment]
没必要合并，可以相互借鉴下。你的代码我看过，写得很好
